apiVersion: v1
entries:
  zlog-collector:
  - apiVersion: v1
    appVersion: 1.15.0
    created: 2019-11-21T14:51:47.062962489-08:00
    description: Zebrium log collector daemonset for Kubernetes.
    digest: ff44fa7e032b203812a0c99424574ff6109aa16b176057ff7c4b3159ce924528
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - logs
    - logging
    - log-management
    - agent
    - events
    - daemonset
    - logger
    maintainers:
    - email: brady@zebrium.com
      name: bradyzuo
    name: zlog-collector
    sources:
    - https://github.com/zebrium/ze-kubernetes-collector
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-kubernetes-collector/master/charts/zlog-collector-1.15.0.tgz
    version: 1.15.0
generated: 2019-11-21T14:51:47.062670469-08:00
