apiVersion: v1
name: zlog-collector
description: Zebrium log collector daemonset for Kubernetes.
version: 1.39.0
appVersion: 1.39.0
keywords:
- logs
- logging
- log-management
- agent
- events
- daemonset
- logger
home: https://www.zebrium.com
icon: https://www.zebrium.com/hubfs/logo2.png
sources:
- https://github.com/zebrium/ze-kubernetes-collector
maintainers:
- name: bradyzuo
  email: brady@zebrium.com
